### ISSUE TITLE
XP Dupe glitch with XP Collector

### ISSUE THREAD

**Issue by jupchurchArke** [Direwolf20-MC/JustDireThings#223]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Found an exploit to dupe XP with XP Collector

### Steps to reproduce

1) Configure XP Collector to collect XP in any range around the block. Leave 0 player xp.
2) While standing in the range, spam shift-click on 'Retrieve XP'. 
3) Watch XP being deposited to the player and collected at the same time, but XP gets duped over and over.

I started with 13 levels and just doing this went well over 100 levels.

### Expected behaviour

Should not dupe XP

**Comment by kalutro** [comment]
There is definitely something wacky going on here. I just attempted this using the same version of JDT 1.4.4, but I am playing the Craftoria pack. Settings are shown in the data. Spam clicking to retrieve xp, then letting it drain xp back from me leaves me with less xp in the block than I started. 

![javaw_07zP1YN0W1](https://github.com/user-attachments/assets/d08a3a9e-6226-4faa-be46-3c9fc872cfd8)

I did a second test and grabbed the data from the block before and after:

Starts at 262726.
![javaw_e0A40EBJDR](https://github.com/user-attachments/assets/26b21531-ba9a-49a3-8e60-9dd063031832)

Ends at 262707.
![javaw_Bj6lx4j9OI](https://github.com/user-attachments/assets/fe4fa178-0323-4af6-bdf2-a1a4cb3c9e9e)

**Comment by jupchurchArke** [comment]
If you shift-click the '-' sign, you get more XP total than you put in. I get it consistently on a custom pack based on the DW20 pack.

**Comment by jupchurchArke** [comment]
https://github.com/user-attachments/assets/d9b30c20-8eed-4479-b3ce-f80fccee53cf

Here's a quick video of it happening. It misbehaves of you don't shift-click, but it dupes hard when you do shift-click.

**Comment by kalutro** [comment]
Definitely some jank in there. In my example, I am holding Shift, though I also tried with Ctrl. Does it still happen when you hold Ctrl instead? I believe this happens if you Retrieve while it's collecting. A simple fix would be to make it instant. You can hold Ctrl and instantly Retrieve and Store all your levels. It's weird that the target level functionality isn't instant, as well.

What's incredible is we are getting opposite results while doing the same thing.

**Comment by jupchurchArke** [comment]
https://github.com/user-attachments/assets/ac9dff16-9578-4b8e-96b5-0759400795ae

With Ctrl-click it's even more pronounced and seems to do the same thing just faster.

**Comment by Direwolf20-MC** [comment]
Yea, the problem is the way xp is stored as an integer vs the way minecraft stores vanilla exp (Which is actually insane). It stores your level as an INT and then your exp bar as a FLOAT that only represents the progress to the next level.  The math gets CRAZY stupid with rounding errors all over the place :). 

I *thought* i had it set to always make you lose (a very small amount) of exp in these scenarios. I'll dig back into the code and see about fixing it.  Thanks for the report!

**Comment by jupchurchArke** [comment]
@Direwolf20-MC I think it might have been a mod interaction behaving in an unexpected way. That was a test world, and I had a Fargo Talisman that increases XP gain from all sources by 50%. That would explain the duping of XP. It's enough of an edge case that it can probably go unfixed. The small loss you noted seems to be in line with what @kalutro was seeing. I'm going to report this as a bug to Fargo since it's his mod that's really the problem.

Thanks!

**Comment by Direwolf20-MC** [comment]
Oh that could definitely explain it :)

**Comment by Direwolf20-MC** [comment]
Yea, the minor loss when spam clicking is unavoidable, i just tested in dev, and theres a tiny loss if you spam click - so just don't do that :).  I can't dupe without fargo - if you find a way to increase EXP without fargo, please let me know.
