### ISSUE TITLE
Energy Transmitter voids energy on certain Powah! blocks.

### ISSUE THREAD

**Issue by kalutro** [Direwolf20-MC/JustDireThings#233]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.66

### Modpack & Version

Craftoria 1.5.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

The Energy Transmitter will send power to the Powah! reactor outputs, essentially voiding it, as the reactor isn't supposed to accept power. This also happens with the Powah! cables. Adding those blocks to the deny list prevents this, though it shouldn't be happening in the first place.

### Steps to reproduce

Place a reactor, fill with supplies and let it run. On one output, place a cable. On a separate output, place an Energy Transmitter. Make sure the Transmitter's range encompasses the cable and a reactor port. Watch the energy be drained from the reactor.

### Expected behaviour

I wouldn't expect energy to be sent to blocks that are output only.

**Comment by Direwolf20-MC** [comment]
So the reason is that the Energy Acceptor has a small amount of energy loss (This is the cost for energy transfer wirelessly).  I forgot to add a book entry for the Energy Acceptor, so that may not have been apparent :).  When you have the cable feeding into the energy acceptor, its sending power wirelessly to the cable, losing a little, and the cable is recharging the transmitter, and repeating for a net loss. 

The issue with the reactor may be on Powah's side, as the transmitter only sends to blocks who 'accept' energy.  That block must be set to accept energy.
