### ISSUE TITLE
[Suggestion] Add side info to Drops Teleporter

### ISSUE THREAD

**Issue by Samtino** [Direwolf20-MC/JustDireThings#24]
QOL Suggestion:

- Add more information to the drops teleporter for the currently selected side of the block for the drops teleporter to prevent possible missclicks on blocks with weird geometry (ie: Mekanism machines)
- Current: `-overworld: [x, y, z]`
- Suggested `-overworld: [x,y,z,side]` 

Additionally if possible/easy
`-overworld: [x,y,z,side]`
`- bound to [blockName]`

![image](https://github.com/Direwolf20-MC/JustDireThings/assets/35015007/1eef7657-fd57-4701-965d-a9b635e6f565)

**Comment by Direwolf20-MC** [comment]
Adding the face is easy -- adding the blockname is less so. Because the tooltip is rendered on client side only, i can't "lookup" the block name its bound to.  So only one of two possible options:

Save the blockname to the tool - but if you bind it to a chest, and break the chest, it'll still report 'Chest' on the tooltip because its only using the name it had saved.

![image](https://github.com/Direwolf20-MC/JustDireThings/assets/39863894/55527c7a-c707-4486-ab40-b23ad1abb4a8)

It can only lookup the block if you're in the same dimension as you the block you bound to (Since the client only knows about the dimension its currently in).
