### ISSUE TITLE
Duplicate issue with ferricore tools and Dimensional Storage

### ISSUE THREAD

**Issue by Saereth** [Direwolf20-MC/JustDireThings#68]
When mining the dimensional tank/chests from Dimensional Storage the ferricore pickaxe dupes the block. Not sure if this is a JustDireThings issue or Dimensional Storage issue but vanilla tools don't have this issue.

https://github.com/Direwolf20-MC/JustDireThings/assets/9200909/25b628af-b08a-4664-afe8-f6a7975a12f9

Issue originally reported here on the FTB Neotech tracker:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5341

**Comment by Direwolf20-MC** [comment]
I think the issue is this line:
https://github.com/Edivad99/DimStorage/blob/1.20.x/src/main/java/edivad/dimstorage/blocks/DimBlockBase.java#L46

Its causing the block to not be turned to 'air' by my methods, and therefore dropping like normal. 

I am not sure if i'm wrong or if this mod is doing it wrong, it very well may be me!

Lets see what happens in 1.21? I think I changed some of this.
