### ISSUE TITLE
(1.21) Potential Bug: Blazegold has the exact same armor level as Ferricore

### ISSUE THREAD

**Issue by Inonedn** [Direwolf20-MC/JustDireThings#85]
isn't it supposed to be stronger? it's identical to its predecessor in terms of armor protection

**Comment by Direwolf20-MC** [comment]
I think I made it the same because its core material is gold. So it’s as strong as iron (stronger than gold) but not stronger than iron. 

Tier 3 armor will have more protection though. 

https://github.com/Direwolf20-MC/JustDireThings/blob/main/src/main/java/com/direwolf20/justdirethings/common/items/armors/utils/ArmorTiers.java
